server:
  port: ${SERVER_PORT:8080}

spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  auth:
    jwks-url: https://dev-8yepzpxgddf187l7.us.auth0.com/.well-known/jwks.json
